"""Add index to messages sender and receiver

Revision ID: 1ed5acfe4691
Revises: 97e3fb276cd5
Create Date: 2026-07-06 15:57:15.007562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed5acfe4691'
down_revision: Union[str, Sequence[str], None] = '97e3fb276cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_receiver', table_name='messages')
    # ### end Alembic commands ###
