"""Add missing user columns

Revision ID: 23e9f9f2022d
Revises: e4f5a6b7c8d9
Create Date: 2026-07-22 19:47:20.335262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e9f9f2022d'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('usuarios', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_usuarios_verification_token'), 'usuarios', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_verification_token'), table_name='usuarios')
    op.drop_column('usuarios', 'verification_token')
    op.drop_column('usuarios', 'is_active')
    # ### end Alembic commands ###
