"""add_cedula_to_usuarios

Revision ID: 40f2fd6d20d0
Revises: 0c3e4bfec771
Create Date: 2026-06-11 18:25:45.500837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f2fd6d20d0'
down_revision: Union[str, Sequence[str], None] = '0c3e4bfec771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cedula', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_column('usuarios', 'cedula')
    # ### end Alembic commands ###
