"""change_telefono_cedula_to_string

Revision ID: 5f42467f58e6
Revises: b91e11366059
Create Date: 2026-06-11 20:12:30.687778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f42467f58e6'
down_revision: Union[str, Sequence[str], None] = 'b91e11366059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.String(length=20),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.String(length=20),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
