"""Add imagenes_repuestos to informes_tecnicos

Revision ID: 6a1188ed4058
Revises: 2057ebe163b3
Create Date: 2026-07-03 16:36:54.083505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1188ed4058'
down_revision: Union[str, Sequence[str], None] = '2057ebe163b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informes_tecnicos', sa.Column('imagenes_repuestos', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes_tecnicos', 'imagenes_repuestos')
    # ### end Alembic commands ###
