"""change_telefono_cedula_to_bigint

Revision ID: b91e11366059
Revises: 40f2fd6d20d0
Create Date: 2026-06-11 20:00:14.589013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91e11366059'
down_revision: Union[str, Sequence[str], None] = '40f2fd6d20d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.BigInteger(),
               nullable=False,
               postgresql_using='telefono::bigint')
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True,
               postgresql_using='cedula::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
